"""Report generation - Markdown and HTML/PDF output.

Generates formatted vulnerability reports from scan results.
--report file.md produces Markdown.
--report file.html produces HTML that prints cleanly to PDF.
"""

from datetime import datetime
from pathlib import Path
from typing import Any

from jinja2 import Template


# ─── Markdown Template ────────────────────────────────────────────────────────

MARKDOWN_TEMPLATE = """# VulNova Vulnerability Report

**Generated:** {{ generated_at }}
**Query:** {{ query }}

---

{% for cve in cves %}
## {{ cve.cve_id }}

| Field | Value |
|-------|-------|
| **CVSS Score** | {{ cve.cvss_score }} ({{ cve.severity }}) |
| **EPSS** | {{ cve.epss_percent }}% |
| **CISA KEV** | {{ "YES - Actively Exploited" if cve.in_kev else "No" }} |
| **Triage Score** | {{ cve.triage_score }}/100 ({{ cve.triage_label }}) |
| **Published** | {{ cve.published }} |

### Description

{{ cve.description }}

### Recommendation

{{ cve.recommendation }}

{% if cve.exploits %}
### Known Exploits

{% for exploit in cve.exploits %}
- **{{ exploit.source }}**: [{{ exploit.name }}]({{ exploit.url }})
{% endfor %}
{% endif %}

{% if cve.nuclei_templates %}
### Nuclei Templates

{% for tmpl in cve.nuclei_templates %}
- `{{ tmpl.path }}` ({{ tmpl.severity }})
  ```
  {{ tmpl.nuclei_command }}
  ```
{% endfor %}
{% endif %}

{% if cve.metasploit_modules %}
### Metasploit Modules

{% for mod in cve.metasploit_modules %}
- **{{ mod.name }}** ({{ mod.type }})
  ```
  {{ mod.use_command }}
  ```
{% endfor %}
{% endif %}

---

{% endfor %}

## Summary

| Metric | Value |
|--------|-------|
| Total CVEs | {{ cves | length }} |
| Critical | {{ cves | selectattr("triage_label", "equalto", "CRITICAL") | list | length }} |
| High | {{ cves | selectattr("triage_label", "equalto", "HIGH") | list | length }} |
| Medium | {{ cves | selectattr("triage_label", "equalto", "MEDIUM") | list | length }} |
| Low | {{ cves | selectattr("triage_label", "equalto", "LOW") | list | length }} |
| In CISA KEV | {{ cves | selectattr("in_kev") | list | length }} |

---
*Report generated by [VulNova](https://github.com/vulnova/vulnova)*
"""

# ─── HTML Template ────────────────────────────────────────────────────────────

HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>VulNova Report - {{ query }}</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            line-height: 1.6; color: #1a1a2e; background: #fff;
            max-width: 900px; margin: 0 auto; padding: 40px 30px;
        }
        h1 { color: #e94560; margin-bottom: 5px; font-size: 28px; }
        h2 { color: #16213e; border-bottom: 2px solid #e94560; padding-bottom: 5px; margin: 30px 0 15px; }
        h3 { color: #0f3460; margin: 20px 0 10px; font-size: 16px; }
        .meta { color: #666; font-size: 14px; margin-bottom: 30px; }
        .cve-card {
            border: 1px solid #e0e0e0; border-radius: 8px;
            padding: 20px; margin: 20px 0; background: #fafafa;
            page-break-inside: avoid;
        }
        .cve-header { display: flex; justify-content: space-between; align-items: center; flex-wrap: wrap; }
        .cve-id { font-size: 20px; font-weight: bold; color: #16213e; }
        .score-badge {
            display: inline-block; padding: 4px 12px; border-radius: 20px;
            font-weight: bold; font-size: 14px; color: white;
        }
        .score-critical { background: #dc3545; }
        .score-high { background: #fd7e14; }
        .score-medium { background: #ffc107; color: #333; }
        .score-low { background: #28a745; }
        .score-info { background: #6c757d; }
        .kev-badge {
            background: #dc3545; color: white; padding: 2px 8px;
            border-radius: 4px; font-size: 12px; font-weight: bold;
        }
        table { width: 100%; border-collapse: collapse; margin: 10px 0; font-size: 14px; }
        th, td { padding: 8px 12px; text-align: left; border-bottom: 1px solid #e0e0e0; }
        th { background: #f5f5f5; font-weight: 600; width: 150px; }
        .description { margin: 15px 0; font-size: 14px; color: #333; }
        .recommendation { background: #e8f5e9; padding: 12px; border-radius: 6px; margin: 10px 0; font-size: 14px; }
        .exploit-list { list-style: none; padding: 0; }
        .exploit-list li { padding: 5px 0; font-size: 14px; }
        .exploit-list a { color: #e94560; text-decoration: none; }
        code { background: #f5f5f5; padding: 2px 6px; border-radius: 3px; font-size: 13px; }
        pre { background: #1a1a2e; color: #e0e0e0; padding: 12px; border-radius: 6px; overflow-x: auto; font-size: 13px; margin: 8px 0; }
        .summary-table { margin-top: 30px; }
        .summary-table td:first-child { font-weight: 600; }
        footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #e0e0e0; color: #666; font-size: 12px; text-align: center; }
        @media print {
            body { padding: 20px; }
            .cve-card { border: 1px solid #ccc; box-shadow: none; }
        }
    </style>
</head>
<body>
    <h1>VulNova Vulnerability Report</h1>
    <p class="meta">Generated: {{ generated_at }} | Query: {{ query }}</p>

    {% for cve in cves %}
    <div class="cve-card">
        <div class="cve-header">
            <span class="cve-id">{{ cve.cve_id }}</span>
            <span>
                {% if cve.in_kev %}<span class="kev-badge">KEV</span>{% endif %}
                <span class="score-badge score-{{ cve.triage_label | lower }}">{{ cve.triage_score }}/100</span>
            </span>
        </div>

        <table>
            <tr><th>CVSS</th><td>{{ cve.cvss_score }} ({{ cve.severity }})</td></tr>
            <tr><th>EPSS</th><td>{{ cve.epss_percent }}% probability</td></tr>
            <tr><th>CISA KEV</th><td>{{ "Actively Exploited" if cve.in_kev else "Not in catalog" }}</td></tr>
            <tr><th>Published</th><td>{{ cve.published }}</td></tr>
        </table>

        <p class="description">{{ cve.description }}</p>

        <div class="recommendation">{{ cve.recommendation }}</div>

        {% if cve.exploits %}
        <h3>Known Exploits</h3>
        <ul class="exploit-list">
            {% for exploit in cve.exploits %}
            <li><strong>{{ exploit.source }}:</strong> <a href="{{ exploit.url }}">{{ exploit.name }}</a></li>
            {% endfor %}
        </ul>
        {% endif %}

        {% if cve.nuclei_templates %}
        <h3>Nuclei Templates</h3>
        {% for tmpl in cve.nuclei_templates %}
        <pre>{{ tmpl.nuclei_command }}</pre>
        {% endfor %}
        {% endif %}

        {% if cve.metasploit_modules %}
        <h3>Metasploit Modules</h3>
        {% for mod in cve.metasploit_modules %}
        <pre>{{ mod.use_command }}</pre>
        {% endfor %}
        {% endif %}
    </div>
    {% endfor %}

    <h2>Summary</h2>
    <table class="summary-table">
        <tr><td>Total CVEs</td><td>{{ cves | length }}</td></tr>
        <tr><td>Critical</td><td>{{ cves | selectattr("triage_label", "equalto", "CRITICAL") | list | length }}</td></tr>
        <tr><td>High</td><td>{{ cves | selectattr("triage_label", "equalto", "HIGH") | list | length }}</td></tr>
        <tr><td>Medium</td><td>{{ cves | selectattr("triage_label", "equalto", "MEDIUM") | list | length }}</td></tr>
        <tr><td>Low</td><td>{{ cves | selectattr("triage_label", "equalto", "LOW") | list | length }}</td></tr>
        <tr><td>In CISA KEV</td><td>{{ cves | selectattr("in_kev") | list | length }}</td></tr>
    </table>

    <footer>
        Report generated by <a href="https://github.com/vulnova/vulnova">VulNova</a>
    </footer>
</body>
</html>
"""


def generate_report(
    output_path: str,
    query: str,
    cve_data: list[dict[str, Any]],
) -> str:
    """Generate a report file (Markdown or HTML based on extension).

    Args:
        output_path: Output file path (.md or .html).
        query: The original search query.
        cve_data: List of CVE data dicts with triage info.

    Returns:
        The absolute path of the generated report.
    """
    path = Path(output_path)
    generated_at = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    context = {
        "generated_at": generated_at,
        "query": query,
        "cves": cve_data,
    }

    if path.suffix.lower() == ".html":
        template = Template(HTML_TEMPLATE)
    else:
        template = Template(MARKDOWN_TEMPLATE)

    content = template.render(**context)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")

    return str(path.resolve())
